# sudo nano sql-deploy.yml

# ansible-playbook sql-deploy.yml

#####

---
- name: Install MySQL on Ubuntu
  hosts: sql
  become: true
  vars:
    ansible_become_pass: 'alex'
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install MySQL packages
      apt:
        name:
          - mysql-server
          - python3-pymysql
        state: present

    - name: Configure MySQL root password
      debconf:
        name: 'mysql-server'
        question: 'mysql-server/root_password'
        value: 'alex'
        vtype: password

    - name: Reconfigure MySQL package with new password
      shell: 'echo "mysql-server-5.7 mysql-server/alex password alex" | debconf-set-selections'

    - name: Restart MySQL service
      service:
        name: mysql
        state: restarted
        enabled: true
